#ifndef __SIMULATION_LIFECYCLE_ERROR_H__
#define __SIMULATION_LIFECYCLE_ERROR_H__

/* STANDARD ERRORS 0-99 */
/* Common errors 0-49 */
#define SUCCESS 0
#define GENERIC_ERROR 1
/* File-related errors 50-74 */
#define FILE_EXISTS_ERROR 50
#define FILE_DOES_NOT_EXIST 51
#define UNABLE_OPEN_FILE 52
#define UNABLE_CLOSE_FILE 53
#define UNABLE_WRITE_FILE 54
/* File-related errors 75-99 */
#define JSON_VALUE_INVALID 75
/** WORKFLOW ERRORS 100-199 **/
// TODO
/** SPATIAL ANALYSIS ERRORS 200-299 **/
// TODO
/** SIMULATION ERRORS 300-399 **/
#define SIM_CONFIG_EMPTY 300
/* model selection issues 305-309 */
#define SIM_MODEL_INVALID 305
#define SIM_MODEL_NOT_FOUND 306
/* model configuration issues 310-320*/
#define SIM_MODEL_CONFIG_INVALID 310
/* feature set issues 320-329 */
#define FEATURE_SET_EMPTY 320
/* relation set issues 330-339 */
#define RELATION_SET_EMPTY 330
#define INCONSISTENT_DATA 335
/* output path issues 340-349 */
#define SIM_CONFIG_OUTPUT_PATH_INVALID 340
#define SIM_RESULT_OUTPUT_PATH_EMPTY 341
#define SIM_RESULT_OUTPUT_PATH_INVALID 342
#define SIM_RESULT_IS_NULL 343
/** VISUALIZATION ERRORS 400-499 */
// TODO

#endif //__SIMULATION_LIFECYCLE_ERROR_H__
