#ifndef __SIMULATION_LIFECYCLE_ERROR_H__
#define __SIMULATION_LIFECYCLE_ERROR_H__

/* STANDARD ERRORS 0-99 */
/* Common errors 0-49 */
#define SUCCESS 0
#define GENERIC_ERROR 1
/* File-related errors 50-99 */
#define FILE_EXISTS_ERROR 50
#define FILE_DOES_NOT_EXIST 51
#define UNABLE_OPEN_FILE 52
#define UNABLE_CLOSE_FILE 53
#define UNABLE_WRITE_FILE 54
/** WORKFLOW ERRORS 100-199 **/
#define WORKFLOW_DOES_NOT_EXIST 100
#define NULL_DATA_SOURCES 101
#define DATA_SOURCE_ID_MISSING 102
#define DATA_SOURCE_PATH_MISSING 103
#define INVALID_DATA_SOURCE_ARGS 104
#define NULL_SPATIAL_ANALYSIS 105
#define NULL_VISUALIZATION 106
#define NULL_SIMULATION 107
#define WORKFLOW_CONTAINS_EMPTY_JSON_OBJ 108
#define DUPLICATE_DATA_SOURCE_ID 109
#define DUPLICATE_DATA_SOURCE_PATH 110
/** SPATIAL ANALYSIS ERRORS 200-299 **/
// TODO
/** SIMULATION ERRORS 300-399 **/
/* model selection issues 300-309 */
#define MODEL_EMPTY 300
#define MODEL_NOT_FOUND 301
/* feature set issues 310-319 */
#define FEATURE_SET_EMPTY 310
/* relation set issues 320-329 */
#define RELATION_SET_EMPTY 320
#define INCONSISTENT_DATA 325
/* output path issues 330-339 */
#define OUTPUT_PATH_EMPTY 330
#define OUTPUT_FILE_EXISTS 331
/** VISUALIZATION ERRORS 400-499 */
// TODO

#endif //__SIMULATION_LIFECYCLE_ERROR_H__
